version: "3.8"

services:
  backend:
    container_name: cpp-backend
    build:
      context: ./cpp-analysis-api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    container_name: react-frontend
    build:
      context: ./final-frontend-step-by-step
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped